---
kind: pipeline
type: docker
name: default

steps:
  
# Add settings.xml to /var/lib/cache/ 
  - name: build
    image: maven
    volumes:
      - name: cache # The Volume's name
        path: /root/.m2 # The path in the container
    commands:
      - mvn help:effective-settings
      - mvn clean package -DskipTests

volumes:
  - name: cache # The name use in this pipeline, 
    host:
      path: /var/lib/cache # The path be used in the host.
